# Generated by Django 5.2.1 on 2025-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_recipe_image_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
