# Generated by Django 5.2.1 on 2025-05-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_alter_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
