# Generated by Django 5.2.1 on 2025-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cuisine', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('total_time', models.IntegerField(help_text='total time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
